-- Insert comprehensive song dataset with 800+ entries across all countries and regions

-- USA Songs (Houston, New York, Los Angeles, Chicago)
INSERT INTO public.songs (title, artist, genre, community_country, community_region, community_age_group, popularity) VALUES
-- Houston
('Sicko Mode', 'Travis Scott', 'Hip-Hop', 'USA', 'Houston', '19-25', 95),
('God''s Plan', 'Drake', 'Hip-Hop', 'USA', 'Houston', '19-25', 93),
('Humble', 'Kendrick Lamar', 'Hip-Hop', 'USA', 'Houston', '19-25', 90),
('Lucid Dreams', 'Juice WRLD', 'Hip-Hop', 'USA', 'Houston', '19-25', 88),
('Rockstar', 'Post Malone', 'Hip-Hop', 'USA', 'Houston', '19-25', 92),
('Sunflower', 'Post Malone', 'Pop', 'USA', 'Houston', '19-25', 89),
('HIGHEST IN THE ROOM', 'Travis Scott', 'Hip-Hop', 'USA', 'Houston', '19-25', 87),
('Franchise', 'Travis Scott', 'Hip-Hop', 'USA', 'Houston', '19-25', 85),
('Butterfly Effect', 'Travis Scott', 'Hip-Hop', 'USA', 'Houston', '19-25', 86),
('Goosebumps', 'Travis Scott', 'Hip-Hop', 'USA', 'Houston', '19-25', 91),
('Dance Monkey', 'Tones and I', 'Pop', 'USA', 'Houston', '13-18', 94),
('Blinding Lights', 'The Weeknd', 'Pop', 'USA', 'Houston', '13-18', 96),
('Levitating', 'Dua Lipa', 'Pop', 'USA', 'Houston', '13-18', 90),
('Circles', 'Post Malone', 'Pop', 'USA', 'Houston', '13-18', 88),
('Someone You Loved', 'Lewis Capaldi', 'Pop', 'USA', 'Houston', '13-18', 87),
('Before You Go', 'Lewis Capaldi', 'Pop', 'USA', 'Houston', '26-40', 85),
('The Box', 'Roddy Ricch', 'Hip-Hop', 'USA', 'Houston', '26-40', 91),
('Life Is Good', 'Future', 'Hip-Hop', 'USA', 'Houston', '26-40', 89),
('Mood', 'iann dior', 'Hip-Hop', 'USA', 'Houston', '26-40', 88),
('Peaches', 'Justin Bieber', 'Pop', 'USA', 'Houston', '26-40', 90),

-- New York
('Empire State of Mind', 'Jay-Z', 'Hip-Hop', 'USA', 'New York', '26-40', 95),
('New York State of Mind', 'Nas', 'Hip-Hop', 'USA', 'New York', '26-40', 93),
('Welcome to New York', 'Taylor Swift', 'Pop', 'USA', 'New York', '19-25', 88),
('No Sleep Till Brooklyn', 'Beastie Boys', 'Rock', 'USA', 'New York', '40+', 90),
('Juicy', 'The Notorious B.I.G.', 'Hip-Hop', 'USA', 'New York', '26-40', 94),
('99 Problems', 'Jay-Z', 'Hip-Hop', 'USA', 'New York', '26-40', 92),
('Big Poppa', 'The Notorious B.I.G.', 'Hip-Hop', 'USA', 'New York', '26-40', 91),
('Hypnotize', 'The Notorious B.I.G.', 'Hip-Hop', 'USA', 'New York', '19-25', 93),
('Shook Ones Pt. II', 'Mobb Deep', 'Hip-Hop', 'USA', 'New York', '26-40', 89),
('N.Y. State of Mind', 'Nas', 'Hip-Hop', 'USA', 'New York', '26-40', 92),
('C.R.E.A.M.', 'Wu-Tang Clan', 'Hip-Hop', 'USA', 'New York', '40+', 94),
('Electric', 'Alina Baraz', 'R&B', 'USA', 'New York', '19-25', 85),
('Location', 'Khalid', 'R&B', 'USA', 'New York', '19-25', 87),
('Boo''d Up', 'Ella Mai', 'R&B', 'USA', 'New York', '19-25', 89),
('Trip', 'Ella Mai', 'R&B', 'USA', 'New York', '13-18', 86),

-- Los Angeles
('California Love', 'Tupac', 'Hip-Hop', 'USA', 'Los Angeles', '40+', 96),
('Hotel California', 'Eagles', 'Rock', 'USA', 'Los Angeles', '40+', 95),
('Californication', 'Red Hot Chili Peppers', 'Rock', 'USA', 'Los Angeles', '26-40', 92),
('Going to California', 'Led Zeppelin', 'Rock', 'USA', 'Los Angeles', '40+', 91),
('Dani California', 'Red Hot Chili Peppers', 'Rock', 'USA', 'Los Angeles', '26-40', 89),
('Still D.R.E.', 'Dr. Dre', 'Hip-Hop', 'USA', 'Los Angeles', '26-40', 94),
('Gin and Juice', 'Snoop Dogg', 'Hip-Hop', 'USA', 'Los Angeles', '26-40', 93),
('Nuthin'' but a ''G'' Thang', 'Dr. Dre', 'Hip-Hop', 'USA', 'Los Angeles', '40+', 95),
('The Next Episode', 'Dr. Dre', 'Hip-Hop', 'USA', 'Los Angeles', '26-40', 92),
('Forgot About Dre', 'Dr. Dre', 'Hip-Hop', 'USA', 'Los Angeles', '26-40', 91),
('Bad Guy', 'Billie Eilish', 'Pop', 'USA', 'Los Angeles', '13-18', 94),
('Therefore I Am', 'Billie Eilish', 'Pop', 'USA', 'Los Angeles', '13-18', 90),
('Lovely', 'Billie Eilish', 'Pop', 'USA', 'Los Angeles', '13-18', 92),
('Ocean Eyes', 'Billie Eilish', 'Pop', 'USA', 'Los Angeles', '19-25', 88),
('When the Party''s Over', 'Billie Eilish', 'Pop', 'USA', 'Los Angeles', '19-25', 87),

-- Chicago
('Go', 'Common', 'Hip-Hop', 'USA', 'Chicago', '26-40', 88),
('Love Lockdown', 'Kanye West', 'Hip-Hop', 'USA', 'Chicago', '26-40', 90),
('Stronger', 'Kanye West', 'Hip-Hop', 'USA', 'Chicago', '19-25', 93),
('Gold Digger', 'Kanye West', 'Hip-Hop', 'USA', 'Chicago', '26-40', 94),
('All of the Lights', 'Kanye West', 'Hip-Hop', 'USA', 'Chicago', '19-25', 91),
('Power', 'Kanye West', 'Hip-Hop', 'USA', 'Chicago', '19-25', 92),
('No Church In The Wild', 'Jay-Z & Kanye West', 'Hip-Hop', 'USA', 'Chicago', '26-40', 89),
('Heartless', 'Kanye West', 'Hip-Hop', 'USA', 'Chicago', '26-40', 90),
('Love Sosa', 'Chief Keef', 'Hip-Hop', 'USA', 'Chicago', '19-25', 87),
('Don''t Like', 'Chief Keef', 'Hip-Hop', 'USA', 'Chicago', '19-25', 86),
('Juice', 'Chance the Rapper', 'Hip-Hop', 'USA', 'Chicago', '19-25', 88),
('No Problem', 'Chance the Rapper', 'Hip-Hop', 'USA', 'Chicago', '19-25', 89),
('Blessings', 'Chance the Rapper', 'Hip-Hop', 'USA', 'Chicago', '26-40', 87),
('Same Drugs', 'Chance the Rapper', 'Hip-Hop', 'USA', 'Chicago', '13-18', 85),
('Cocoa Butter Kisses', 'Chance the Rapper', 'Hip-Hop', 'USA', 'Chicago', '13-18', 86),

-- UK Songs (London, Manchester, Birmingham)
-- London
('Someone Like You', 'Adele', 'Pop', 'UK', 'London', '26-40', 96),
('Hello', 'Adele', 'Pop', 'UK', 'London', '26-40', 95),
('Rolling in the Deep', 'Adele', 'Pop', 'UK', 'London', '26-40', 94),
('Shape of You', 'Ed Sheeran', 'Pop', 'UK', 'London', '19-25', 97),
('Perfect', 'Ed Sheeran', 'Pop', 'UK', 'London', '19-25', 95),
('Thinking Out Loud', 'Ed Sheeran', 'Pop', 'UK', 'London', '26-40', 93),
('Photograph', 'Ed Sheeran', 'Pop', 'UK', 'London', '19-25', 91),
('Castle on the Hill', 'Ed Sheeran', 'Pop', 'UK', 'London', '19-25', 89),
('Shivers', 'Ed Sheeran', 'Pop', 'UK', 'London', '19-25', 92),
('Bad Habits', 'Ed Sheeran', 'Pop', 'UK', 'London', '13-18', 93),
('Stay With Me', 'Sam Smith', 'Pop', 'UK', 'London', '26-40', 90),
('Too Good at Goodbyes', 'Sam Smith', 'Pop', 'UK', 'London', '19-25', 88),
('I''m Not the Only One', 'Sam Smith', 'Pop', 'UK', 'London', '26-40', 89),
('Latch', 'Disclosure', 'Electronic', 'UK', 'London', '19-25', 91),
('Omen', 'Disclosure', 'Electronic', 'UK', 'London', '19-25', 87),
('Magnets', 'Disclosure', 'Electronic', 'UK', 'London', '19-25', 86),
('When Love Takes Over', 'David Guetta', 'Electronic', 'UK', 'London', '26-40', 92),
('Titanium', 'David Guetta', 'Electronic', 'UK', 'London', '19-25', 94),
('Without You', 'David Guetta', 'Electronic', 'UK', 'London', '13-18', 88),
('Lean On', 'Major Lazer', 'Electronic', 'UK', 'London', '19-25', 93),

-- Manchester
('Blue Monday', 'New Order', 'Electronic', 'UK', 'Manchester', '40+', 92),
('Love Will Tear Us Apart', 'Joy Division', 'Rock', 'UK', 'Manchester', '40+', 93),
('There Is a Light', 'The Smiths', 'Rock', 'UK', 'Manchester', '40+', 91),
('How Soon Is Now?', 'The Smiths', 'Rock', 'UK', 'Manchester', '40+', 90),
('This Charming Man', 'The Smiths', 'Rock', 'UK', 'Manchester', '40+', 89),
('Wonderwall', 'Oasis', 'Rock', 'UK', 'Manchester', '26-40', 96),
('Don''t Look Back in Anger', 'Oasis', 'Rock', 'UK', 'Manchester', '26-40', 95),
('Champagne Supernova', 'Oasis', 'Rock', 'UK', 'Manchester', '26-40', 93),
('Live Forever', 'Oasis', 'Rock', 'UK', 'Manchester', '26-40', 92),
('Supersonic', 'Oasis', 'Rock', 'UK', 'Manchester', '26-40', 90),
('Step On', 'Happy Mondays', 'Rock', 'UK', 'Manchester', '40+', 87),
('Fools Gold', 'The Stone Roses', 'Rock', 'UK', 'Manchester', '40+', 88),
('I Wanna Be Adored', 'The Stone Roses', 'Rock', 'UK', 'Manchester', '40+', 89),
('She Bangs the Drums', 'The Stone Roses', 'Rock', 'UK', 'Manchester', '40+', 86),
('Waterfall', 'The Stone Roses', 'Rock', 'UK', 'Manchester', '40+', 85),

-- Birmingham
('Go Your Own Way', 'Fleetwood Mac', 'Rock', 'UK', 'Birmingham', '40+', 94),
('Dreams', 'Fleetwood Mac', 'Rock', 'UK', 'Birmingham', '40+', 95),
('The Chain', 'Fleetwood Mac', 'Rock', 'UK', 'Birmingham', '40+', 92),
('Mr. Blue Sky', 'Electric Light Orchestra', 'Rock', 'UK', 'Birmingham', '40+', 93),
('Don''t Bring Me Down', 'Electric Light Orchestra', 'Rock', 'UK', 'Birmingham', '40+', 90),
('Living Thing', 'Electric Light Orchestra', 'Rock', 'UK', 'Birmingham', '40+', 89),
('Paranoid', 'Black Sabbath', 'Rock', 'UK', 'Birmingham', '40+', 91),
('Iron Man', 'Black Sabbath', 'Rock', 'UK', 'Birmingham', '40+', 92),
('War Pigs', 'Black Sabbath', 'Rock', 'UK', 'Birmingham', '40+', 90),
('Changes', 'Black Sabbath', 'Rock', 'UK', 'Birmingham', '40+', 87),
('Tears Don''t Fall', 'Bullet for My Valentine', 'Rock', 'UK', 'Birmingham', '19-25', 86),
('Scream Aim Fire', 'Bullet for My Valentine', 'Rock', 'UK', 'Birmingham', '19-25', 85),
('Waking the Demon', 'Bullet for My Valentine', 'Rock', 'UK', 'Birmingham', '19-25', 84),
('All These Things I Hate', 'Bullet for My Valentine', 'Rock', 'UK', 'Birmingham', '13-18', 83),
('Your Betrayal', 'Bullet for My Valentine', 'Rock', 'UK', 'Birmingham', '19-25', 85),

-- India Songs (Delhi, Mumbai, Bengaluru, Chennai, Hyderabad, Pune, Calicut)
-- Delhi
('Kesariya', 'Arijit Singh', 'Bollywood', 'India', 'Delhi', '19-25', 96),
('Apna Bana Le', 'Arijit Singh', 'Bollywood', 'India', 'Delhi', '19-25', 94),
('Raatan Lambiyan', 'Jubin Nautiyal', 'Bollywood', 'India', 'Delhi', '19-25', 93),
('Srivalli', 'Javed Ali', 'Bollywood', 'India', 'Delhi', '13-18', 92),
('Saami Saami', 'Mounika Iyer', 'Bollywood', 'India', 'Delhi', '13-18', 90),
('Manike', 'Yohani', 'Pop', 'India', 'Delhi', '13-18', 89),
('Natu Natu', 'Rahul Sipligunj', 'Bollywood', 'India', 'Delhi', '19-25', 95),
('Kacha Badam', 'Bhuban Badyakar', 'Folk', 'India', 'Delhi', '13-18', 87),
('Pasoori', 'Ali Sethi', 'Pop', 'India', 'Delhi', '19-25', 91),
('Excuses', 'AP Dhillon', 'Punjabi', 'India', 'Delhi', '19-25', 90),
('Brown Munde', 'AP Dhillon', 'Punjabi', 'India', 'Delhi', '19-25', 92),
('Insane', 'AP Dhillon', 'Punjabi', 'India', 'Delhi', '19-25', 88),
('295', 'Sidhu Moose Wala', 'Punjabi', 'India', 'Delhi', '19-25', 91),
('So High', 'Sidhu Moose Wala', 'Punjabi', 'India', 'Delhi', '19-25', 89),
('Legend', 'Sidhu Moose Wala', 'Punjabi', 'India', 'Delhi', '26-40', 90),

-- Mumbai
('Tum Hi Ho', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '26-40', 97),
('Channa Mereya', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '26-40', 95),
('Agar Tum Saath Ho', 'Alka Yagnik', 'Bollywood', 'India', 'Mumbai', '26-40', 94),
('Phir Bhi Tumko Chaahunga', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '19-25', 93),
('Bekhayali', 'Sachet Tandon', 'Bollywood', 'India', 'Mumbai', '19-25', 92),
('Shayad', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '19-25', 91),
('Tujhe Kitna Chahne Lage', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '26-40', 90),
('Pachtaoge', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '19-25', 89),
('Kaise Hua', 'Vishal Mishra', 'Bollywood', 'India', 'Mumbai', '13-18', 88),
('Ve Maahi', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '13-18', 87),
('Besharam Rang', 'Shilpa Rao', 'Bollywood', 'India', 'Mumbai', '19-25', 93),
('Jhoome Jo Pathaan', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '19-25', 91),
('Bolo Har Har Har', 'Badshah', 'Bollywood', 'India', 'Mumbai', '13-18', 86),
('Garmi', 'Neha Kakkar', 'Bollywood', 'India', 'Mumbai', '13-18', 88),
('Illegal Weapon 2.0', 'Jasmine Sandlas', 'Punjabi', 'India', 'Mumbai', '19-25', 87),

-- Bengaluru
('Rowdy Baby', 'Dhanush', 'Tamil', 'India', 'Bengaluru', '19-25', 95),
('Vaathi Coming', 'Anirudh', 'Tamil', 'India', 'Bengaluru', '19-25', 93),
('Kutti Story', 'Anirudh', 'Tamil', 'India', 'Bengaluru', '13-18', 91),
('Master the Blaster', 'Anirudh', 'Tamil', 'India', 'Bengaluru', '13-18', 89),
('Oo Antava', 'Indravathi Chauhan', 'Telugu', 'India', 'Bengaluru', '19-25', 94),
('Saami Saami', 'Sid Sriram', 'Telugu', 'India', 'Bengaluru', '19-25', 92),
('Buttabomma', 'Armaan Malik', 'Telugu', 'India', 'Bengaluru', '19-25', 93),
('Butta Bomma', 'Armaan Malik', 'Telugu', 'India', 'Bengaluru', '13-18', 90),
('Ramuloo Ramulaa', 'Anurag Kulkarni', 'Telugu', 'India', 'Bengaluru', '13-18', 89),
('Arabic Kuthu', 'Anirudh', 'Tamil', 'India', 'Bengaluru', '13-18', 94),
('Halamithi Habibo', 'Anirudh', 'Tamil', 'India', 'Bengaluru', '19-25', 88),
('Kannaana Kanney', 'Sid Sriram', 'Tamil', 'India', 'Bengaluru', '26-40', 87),
('Kaavaalaa', 'Shilpa Rao', 'Tamil', 'India', 'Bengaluru', '19-25', 91),
('Chaleya', 'Arijit Singh', 'Hindi', 'India', 'Bengaluru', '19-25', 90),
('Zihaal e Miskin', 'Vishal Mishra', 'Hindi', 'India', 'Bengaluru', '26-40', 88),

-- Chennai
('Vaathi Coming', 'Gana Balachander', 'Tamil', 'India', 'Chennai', '19-25', 94),
('Arabic Kuthu', 'Jonita Gandhi', 'Tamil', 'India', 'Chennai', '13-18', 95),
('Rowdy Baby', 'Dhee', 'Tamil', 'India', 'Chennai', '19-25', 96),
('Aaluma Doluma', 'Kaushik Krish', 'Tamil', 'India', 'Chennai', '19-25', 89),
('Surviva', 'Yogi B', 'Tamil', 'India', 'Chennai', '19-25', 88),
('Thalli Pogathey', 'Sid Sriram', 'Tamil', 'India', 'Chennai', '26-40', 92),
('Kanave Kanave', 'Anirudh', 'Tamil', 'India', 'Chennai', '19-25', 90),
('Po Indru Neeyaga', 'Sid Sriram', 'Tamil', 'India', 'Chennai', '26-40', 87),
('Azhagiye', 'Sid Sriram', 'Tamil', 'India', 'Chennai', '26-40', 86),
('Mudhal Nee Mudivum Nee', 'Sid Sriram', 'Tamil', 'India', 'Chennai', '19-25', 91),
('Hey Mama', 'Benny Dayal', 'Tamil', 'India', 'Chennai', '13-18', 85),
('Vaa Vaathi', 'Santhosh Narayanan', 'Tamil', 'India', 'Chennai', '13-18', 84),
('Sodakku', 'Anthony Daasan', 'Tamil', 'India', 'Chennai', '19-25', 83),
('Combo', 'Vivek', 'Tamil', 'India', 'Chennai', '13-18', 82),
('Deva Deva', 'Arijit Singh', 'Hindi', 'India', 'Chennai', '19-25', 90),

-- Hyderabad
('Oo Antava', 'Indravathi Chauhan', 'Telugu', 'India', 'Hyderabad', '19-25', 95),
('Butta Bomma', 'Armaan Malik', 'Telugu', 'India', 'Hyderabad', '19-25', 94),
('Saami Saami', 'Sid Sriram', 'Telugu', 'India', 'Hyderabad', '19-25', 93),
('Ramuloo Ramulaa', 'Anurag Kulkarni', 'Telugu', 'India', 'Hyderabad', '13-18', 91),
('Rang De', 'Yazin Nizar', 'Telugu', 'India', 'Hyderabad', '19-25', 90),
('Inkem Inkem', 'Sid Sriram', 'Telugu', 'India', 'Hyderabad', '26-40', 92),
('Yenti Yenti', 'Chinmayi', 'Telugu', 'India', 'Hyderabad', '26-40', 89),
('Manohari', 'Swetha Mohan', 'Telugu', 'India', 'Hyderabad', '26-40', 88),
('Seeti Maar', 'Devi Sri Prasad', 'Telugu', 'India', 'Hyderabad', '13-18', 87),
('Dhamaka', 'Riya Vaidya', 'Telugu', 'India', 'Hyderabad', '13-18', 86),
('Srivalli', 'Javed Ali', 'Telugu', 'India', 'Hyderabad', '19-25', 93),
('Oh Sita Hey Rama', 'Sid Sriram', 'Telugu', 'India', 'Hyderabad', '19-25', 89),
('Komuram Bheemudo', 'Kaala Bhairava', 'Telugu', 'India', 'Hyderabad', '26-40', 90),
('Etthara Jenda', 'Devi Sri Prasad', 'Telugu', 'India', 'Hyderabad', '13-18', 85),
('Alludu Adhurs', 'Benny Dayal', 'Telugu', 'India', 'Hyderabad', '13-18', 84),

-- Pune
('Zingaat', 'Ajay Gogavale', 'Marathi', 'India', 'Pune', '19-25', 93),
('Kombdi Palali', 'Avadhoot Gupte', 'Marathi', 'India', 'Pune', '13-18', 91),
('Gulabi Sadi', 'Shreya Ghoshal', 'Marathi', 'India', 'Pune', '19-25', 89),
('Apsara Aali', 'Shreya Ghoshal', 'Marathi', 'India', 'Pune', '26-40', 90),
('Aala Re Aala', 'Ajay-Atul', 'Marathi', 'India', 'Pune', '19-25', 88),
('Dharla Tar Tula', 'Amitraj', 'Marathi', 'India', 'Pune', '19-25', 86),
('Bhingri', 'Ajay-Atul', 'Marathi', 'India', 'Pune', '13-18', 87),
('Jeev Rangala', 'Ajay-Atul', 'Marathi', 'India', 'Pune', '26-40', 91),
('Yad Lagla', 'Ajay-Atul', 'Marathi', 'India', 'Pune', '26-40', 89),
('Morya', 'Vaishali Samant', 'Marathi', 'India', 'Pune', '13-18', 85),
('Ved Lagale', 'Swapnil Bandodkar', 'Marathi', 'India', 'Pune', '19-25', 84),
('Khel Mandala', 'Shreya Ghoshal', 'Marathi', 'India', 'Pune', '19-25', 86),
('Aai Shapat', 'Avadhoot Gupte', 'Marathi', 'India', 'Pune', '26-40', 87),
('Jagla Prema Jaga', 'Ajay Gogavale', 'Marathi', 'India', 'Pune', '26-40', 85),
('Bindast', 'Amitraj', 'Marathi', 'India', 'Pune', '13-18', 83),

-- Calicut
('Kaavaalaa', 'Shilpa Rao', 'Malayalam', 'India', 'Calicut', '19-25', 92),
('Jimikki Kammal', 'Vineeth Sreenivasan', 'Malayalam', 'India', 'Calicut', '13-18', 94),
('Manike Mage Hithe', 'Yohani', 'Pop', 'India', 'Calicut', '13-18', 90),
('Pazhaya Vannarapettai', 'Hesham Abdul Wahab', 'Malayalam', 'India', 'Calicut', '19-25', 88),
('Nilaave Vaa', 'A.R. Rahman', 'Tamil', 'India', 'Calicut', '26-40', 91),
('Arabic Kuthu', 'Anirudh', 'Tamil', 'India', 'Calicut', '13-18', 93),
('Megham Karukatha', 'Vijay Yesudas', 'Malayalam', 'India', 'Calicut', '26-40', 87),
('Kanmaniye', 'Haricharan', 'Malayalam', 'India', 'Calicut', '19-25', 86),
('Pathivaayi Njan', 'Vijay Yesudas', 'Malayalam', 'India', 'Calicut', '26-40', 89),
('Chundari Penne', 'Shreya Ghoshal', 'Malayalam', 'India', 'Calicut', '19-25', 85),
('Malare', 'Vijay Yesudas', 'Malayalam', 'India', 'Calicut', '26-40', 90),
('Entammede Jimikki Kammal', 'Vineeth Sreenivasan', 'Malayalam', 'India', 'Calicut', '13-18', 91),
('Aaromale', 'Vineeth Sreenivasan', 'Malayalam', 'India', 'Calicut', '19-25', 87),
('Varaha Roopam', 'Kailash Kher', 'Malayalam', 'India', 'Calicut', '26-40', 88),
('Pularikalo', 'Shreya Ghoshal', 'Malayalam', 'India', 'Calicut', '19-25', 84),

-- Japan Songs (Tokyo, Osaka, Kyoto)
-- Tokyo
('Lemon', 'Kenshi Yonezu', 'J-Pop', 'Japan', 'Tokyo', '19-25', 97),
('Pretender', 'Official HIGE DANdism', 'J-Pop', 'Japan', 'Tokyo', '19-25', 96),
('Gurenge', 'LiSA', 'J-Pop', 'Japan', 'Tokyo', '13-18', 95),
('Homura', 'LiSA', 'J-Pop', 'Japan', 'Tokyo', '13-18', 94),
('Shiawase', 'back number', 'J-Pop', 'Japan', 'Tokyo', '26-40', 92),
('Ito', 'Aimyon', 'J-Pop', 'Japan', 'Tokyo', '19-25', 91),
('Marigold', 'Aimyon', 'J-Pop', 'Japan', 'Tokyo', '19-25', 90),
('Koi', 'Gen Hoshino', 'J-Pop', 'Japan', 'Tokyo', '26-40', 93),
('Doraemon', 'Gen Hoshino', 'J-Pop', 'Japan', 'Tokyo', '13-18', 89),
('Kaibutsu', 'YOASOBI', 'J-Pop', 'Japan', 'Tokyo', '13-18', 94),
('Yoru ni Kakeru', 'YOASOBI', 'J-Pop', 'Japan', 'Tokyo', '13-18', 95),
('Gunjou', 'YOASOBI', 'J-Pop', 'Japan', 'Tokyo', '13-18', 92),
('Ano Yume wo Nazotte', 'YOASOBI', 'J-Pop', 'Japan', 'Tokyo', '13-18', 91),
('Racing into the Night', 'YOASOBI', 'J-Pop', 'Japan', 'Tokyo', '19-25', 93),
('Monster', 'YOASOBI', 'J-Pop', 'Japan', 'Tokyo', '13-18', 90),

-- Osaka
('First Love', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '40+', 96),
('Automatic', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '40+', 94),
('Can You Keep A Secret?', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '26-40', 92),
('Flavor Of Life', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '26-40', 93),
('Prisoner Of Love', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '26-40', 91),
('Beautiful World', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '26-40', 90),
('Kiss & Cry', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '40+', 89),
('Addicted To You', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '40+', 91),
('SAKURA Drops', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '40+', 90),
('Eternally', 'Utada Hikaru', 'J-Pop', 'Japan', 'Osaka', '26-40', 88),
('Love So Sweet', 'Arashi', 'J-Pop', 'Japan', 'Osaka', '26-40', 92),
('Happiness', 'Arashi', 'J-Pop', 'Japan', 'Osaka', '26-40', 89),
('Monster', 'Arashi', 'J-Pop', 'Japan', 'Osaka', '19-25', 87),
('Sakura', 'Arashi', 'J-Pop', 'Japan', 'Osaka', '26-40', 88),
('Wish', 'Arashi', 'J-Pop', 'Japan', 'Osaka', '19-25', 86),

-- Kyoto
('Senbonzakura', 'Wagakki Band', 'J-Rock', 'Japan', 'Kyoto', '19-25', 93),
('Kishikaisei', 'Wagakki Band', 'J-Rock', 'Japan', 'Kyoto', '19-25', 90),
('Valkyrie', 'Wagakki Band', 'J-Rock', 'Japan', 'Kyoto', '19-25', 89),
('Tengaku', 'Wagakki Band', 'J-Rock', 'Japan', 'Kyoto', '19-25', 88),
('Hanabi', 'Mr.Children', 'J-Rock', 'Japan', 'Kyoto', '26-40', 92),
('Sign', 'Mr.Children', 'J-Rock', 'Japan', 'Kyoto', '26-40', 91),
('Gift', 'Mr.Children', 'J-Pop', 'Japan', 'Kyoto', '26-40', 89),
('Kurumi', 'Mr.Children', 'J-Pop', 'Japan', 'Kyoto', '40+', 90),
('Sakura', 'Ikimono-gakari', 'J-Pop', 'Japan', 'Kyoto', '26-40', 91),
('YELL', 'Ikimono-gakari', 'J-Pop', 'Japan', 'Kyoto', '19-25', 88),
('Arigatou', 'Ikimono-gakari', 'J-Pop', 'Japan', 'Kyoto', '26-40', 87),
('Hotaru no Hikari', 'Ikimono-gakari', 'J-Pop', 'Japan', 'Kyoto', '26-40', 86),
('Natsubunishite', 'Ikimono-gakari', 'J-Pop', 'Japan', 'Kyoto', '19-25', 85),
('Kimagure Romantic', 'Ikimono-gakari', 'J-Pop', 'Japan', 'Kyoto', '19-25', 84),
('Blue Bird', 'Ikimono-gakari', 'J-Pop', 'Japan', 'Kyoto', '13-18', 86),

-- South Korea Songs (Seoul, Busan, Incheon)
-- Seoul
('Dynamite', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '13-18', 98),
('Butter', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '13-18', 97),
('Boy With Luv', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '13-18', 96),
('Life Goes On', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '19-25', 94),
('ON', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '19-25', 93),
('Black Swan', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '19-25', 92),
('DNA', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '13-18', 95),
('IDOL', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '13-18', 94),
('Fake Love', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '19-25', 93),
('Spring Day', 'BTS', 'K-Pop', 'South Korea', 'Seoul', '19-25', 96),
('How You Like That', 'BLACKPINK', 'K-Pop', 'South Korea', 'Seoul', '13-18', 97),
('Kill This Love', 'BLACKPINK', 'K-Pop', 'South Korea', 'Seoul', '13-18', 96),
('DDU-DU DDU-DU', 'BLACKPINK', 'K-Pop', 'South Korea', 'Seoul', '13-18', 95),
('Pink Venom', 'BLACKPINK', 'K-Pop', 'South Korea', 'Seoul', '13-18', 94),
('Shut Down', 'BLACKPINK', 'K-Pop', 'South Korea', 'Seoul', '19-25', 93),

-- Busan
('Ditto', 'NewJeans', 'K-Pop', 'South Korea', 'Busan', '13-18', 96),
('Hype Boy', 'NewJeans', 'K-Pop', 'South Korea', 'Busan', '13-18', 95),
('OMG', 'NewJeans', 'K-Pop', 'South Korea', 'Busan', '13-18', 94),
('Attention', 'NewJeans', 'K-Pop', 'South Korea', 'Busan', '13-18', 93),
('Cookie', 'NewJeans', 'K-Pop', 'South Korea', 'Busan', '13-18', 91),
('Love Dive', 'IVE', 'K-Pop', 'South Korea', 'Busan', '13-18', 95),
('ELEVEN', 'IVE', 'K-Pop', 'South Korea', 'Busan', '13-18', 94),
('After LIKE', 'IVE', 'K-Pop', 'South Korea', 'Busan', '13-18', 93),
('Kitsch', 'IVE', 'K-Pop', 'South Korea', 'Busan', '13-18', 91),
('I AM', 'IVE', 'K-Pop', 'South Korea', 'Busan', '19-25', 90),
('Nxde', 'G(I-DLE)', 'K-Pop', 'South Korea', 'Busan', '19-25', 92),
('Tomboy', 'G(I-DLE)', 'K-Pop', 'South Korea', 'Busan', '19-25', 93),
('Oh My God', 'G(I-DLE)', 'K-Pop', 'South Korea', 'Busan', '19-25', 89),
('LATATA', 'G(I-DLE)', 'K-Pop', 'South Korea', 'Busan', '19-25', 88),
('Queencard', 'G(I-DLE)', 'K-Pop', 'South Korea', 'Busan', '13-18', 94),

-- Incheon
('Antifragile', 'LE SSERAFIM', 'K-Pop', 'South Korea', 'Incheon', '13-18', 95),
('FEARLESS', 'LE SSERAFIM', 'K-Pop', 'South Korea', 'Incheon', '13-18', 93),
('Unforgiven', 'LE SSERAFIM', 'K-Pop', 'South Korea', 'Incheon', '13-18', 92),
('Eve, Psyche & The Bluebeard''s wife', 'LE SSERAFIM', 'K-Pop', 'South Korea', 'Incheon', '19-25', 91),
('EASY', 'LE SSERAFIM', 'K-Pop', 'South Korea', 'Incheon', '19-25', 90),
('Seven (feat. Latto)', 'Jungkook', 'K-Pop', 'South Korea', 'Incheon', '19-25', 96),
('Left and Right', 'Charlie Puth', 'Pop', 'South Korea', 'Incheon', '19-25', 92),
('That That', 'PSY', 'K-Pop', 'South Korea', 'Incheon', '26-40', 89),
('Gangnam Style', 'PSY', 'K-Pop', 'South Korea', 'Incheon', '26-40', 95),
('Gentleman', 'PSY', 'K-Pop', 'South Korea', 'Incheon', '26-40', 91),
('Hangover', 'PSY', 'K-Pop', 'South Korea', 'Incheon', '26-40', 87),
('Flower', 'Jisoo', 'K-Pop', 'South Korea', 'Incheon', '19-25', 94),
('SOLO', 'Jennie', 'K-Pop', 'South Korea', 'Incheon', '19-25', 93),
('Gone', 'Rose', 'K-Pop', 'South Korea', 'Incheon', '19-25', 90),
('On The Ground', 'Rose', 'K-Pop', 'South Korea', 'Incheon', '19-25', 92),

-- France Songs (Paris, Lyon, Marseille)
-- Paris
('La Vie en Rose', 'Edith Piaf', 'Chanson', 'France', 'Paris', '40+', 96),
('Non, Je Ne Regrette Rien', 'Edith Piaf', 'Chanson', 'France', 'Paris', '40+', 95),
('Sous le Ciel de Paris', 'Edith Piaf', 'Chanson', 'France', 'Paris', '40+', 93),
('Padam Padam', 'Edith Piaf', 'Chanson', 'France', 'Paris', '40+', 91),
('Hymne à l''Amour', 'Edith Piaf', 'Chanson', 'France', 'Paris', '40+', 94),
('Dernière Danse', 'Indila', 'Pop', 'France', 'Paris', '19-25', 95),
('Tourner Dans Le Vide', 'Indila', 'Pop', 'France', 'Paris', '19-25', 92),
('Love Story', 'Indila', 'Pop', 'France', 'Paris', '19-25', 90),
('S.O.S', 'Indila', 'Pop', 'France', 'Paris', '19-25', 88),
('Ainsi Bas La Vida', 'Indila', 'Pop', 'France', 'Paris', '26-40', 89),
('Djadja', 'Aya Nakamura', 'Pop', 'France', 'Paris', '19-25', 94),
('Pookie', 'Aya Nakamura', 'Pop', 'France', 'Paris', '19-25', 91),
('Copines', 'Aya Nakamura', 'Pop', 'France', 'Paris', '19-25', 90),
('La Dot', 'Aya Nakamura', 'Pop', 'France', 'Paris', '13-18', 87),
('Jolie Nana', 'Aya Nakamura', 'Pop', 'France', 'Paris', '13-18', 89),

-- Lyon
('Formidable', 'Stromae', 'Pop', 'France', 'Lyon', '19-25', 93),
('Papaoutai', 'Stromae', 'Pop', 'France', 'Lyon', '19-25', 95),
('Tous Les Mêmes', 'Stromae', 'Pop', 'France', 'Lyon', '19-25', 92),
('Ave Cesaria', 'Stromae', 'Pop', 'France', 'Lyon', '26-40', 89),
('Carmen', 'Stromae', 'Pop', 'France', 'Lyon', '26-40', 90),
('Alors On Danse', 'Stromae', 'Electronic', 'France', 'Lyon', '19-25', 94),
('Santé', 'Stromae', 'Pop', 'France', 'Lyon', '19-25', 91),
('L''Enfer', 'Stromae', 'Pop', 'France', 'Lyon', '26-40', 88),
('Fils de Joie', 'Stromae', 'Pop', 'France', 'Lyon', '26-40', 87),
('Riez', 'Stromae', 'Pop', 'France', 'Lyon', '19-25', 86),
('C''est la Vie', 'Khaled', 'Raï', 'France', 'Lyon', '40+', 92),
('Aicha', 'Khaled', 'Raï', 'France', 'Lyon', '40+', 93),
('Didi', 'Khaled', 'Raï', 'France', 'Lyon', '40+', 91),
('Abdel Kader', 'Khaled', 'Raï', 'France', 'Lyon', '40+', 89),
('Alech Taadi', 'Khaled', 'Raï', 'France', 'Lyon', '26-40', 87),

-- Marseille
('La Marseillaise', 'Claude Joseph Rouget de Lisle', 'Classical', 'France', 'Marseille', '40+', 95),
('Comme d''habitude', 'Claude François', 'Chanson', 'France', 'Marseille', '40+', 92),
('Alexandrie Alexandra', 'Claude François', 'Chanson', 'France', 'Marseille', '40+', 90),
('Le Lundi au Soleil', 'Claude François', 'Chanson', 'France', 'Marseille', '40+', 89),
('Magnolias For Ever', 'Claude François', 'Chanson', 'France', 'Marseille', '40+', 87),
('Bande Organisée', 'Jul', 'Rap', 'France', 'Marseille', '19-25', 94),
('Dans Ma Paranoïa', 'Jul', 'Rap', 'France', 'Marseille', '19-25', 91),
('On M''Appelle L''Ovni', 'Jul', 'Rap', 'France', 'Marseille', '19-25', 89),
('Wesh Alors', 'Jul', 'Rap', 'France', 'Marseille', '19-25', 88),
('Tchikita', 'Jul', 'Rap', 'France', 'Marseille', '13-18', 90),
('Bella', 'Maître Gims', 'Pop', 'France', 'Marseille', '19-25', 93),
('Sapés Comme Jamais', 'Maître Gims', 'Pop', 'France', 'Marseille', '19-25', 91),
('Est-ce Que Tu M''Aimes?', 'Maître Gims', 'Pop', 'France', 'Marseille', '26-40', 89),
('J''Me Tire', 'Maître Gims', 'Pop', 'France', 'Marseille', '19-25', 92),
('Malheur Malheur', 'Maître Gims', 'Pop', 'France', 'Marseille', '19-25', 87),

-- Additional diverse entries for all regions to reach 800+
-- More USA entries
('Flowers', 'Miley Cyrus', 'Pop', 'USA', 'Houston', '19-25', 96),
('Anti-Hero', 'Taylor Swift', 'Pop', 'USA', 'Houston', '19-25', 95),
('As It Was', 'Harry Styles', 'Pop', 'USA', 'Houston', '13-18', 94),
('Heat Waves', 'Glass Animals', 'Indie', 'USA', 'Houston', '19-25', 92),
('STAY', 'The Kid LAROI', 'Pop', 'USA', 'Houston', '13-18', 93),
('Good 4 U', 'Olivia Rodrigo', 'Pop', 'USA', 'Houston', '13-18', 94),
('Drivers License', 'Olivia Rodrigo', 'Pop', 'USA', 'Houston', '13-18', 95),
('Traitor', 'Olivia Rodrigo', 'Pop', 'USA', 'Houston', '13-18', 90),
('Wake Me Up', 'Avicii', 'Electronic', 'USA', 'New York', '19-25', 94),
('The Nights', 'Avicii', 'Electronic', 'USA', 'New York', '19-25', 91),
('Levels', 'Avicii', 'Electronic', 'USA', 'New York', '19-25', 92),
('Hey Brother', 'Avicii', 'Electronic', 'USA', 'New York', '13-18', 89),
('Waiting For Love', 'Avicii', 'Electronic', 'USA', 'New York', '13-18', 88),
('Without You', 'Avicii', 'Electronic', 'USA', 'Los Angeles', '19-25', 87),
('Lonely', 'Justin Bieber', 'Pop', 'USA', 'Los Angeles', '19-25', 91),
('Yummy', 'Justin Bieber', 'Pop', 'USA', 'Los Angeles', '13-18', 89),
('Intentions', 'Justin Bieber', 'Pop', 'USA', 'Los Angeles', '13-18', 90),
('Holy', 'Justin Bieber', 'Pop', 'USA', 'Los Angeles', '13-18', 88),
('Anyone', 'Justin Bieber', 'Pop', 'USA', 'Chicago', '19-25', 87),
('Ghost', 'Justin Bieber', 'Pop', 'USA', 'Chicago', '13-18', 89),

-- More UK entries
('Starboy', 'The Weeknd', 'R&B', 'UK', 'London', '19-25', 93),
('Blinding Lights', 'The Weeknd', 'Pop', 'UK', 'London', '19-25', 96),
('Save Your Tears', 'The Weeknd', 'Pop', 'UK', 'London', '19-25', 92),
('I Feel It Coming', 'The Weeknd', 'R&B', 'UK', 'London', '26-40', 90),
('Can''t Feel My Face', 'The Weeknd', 'Pop', 'UK', 'London', '19-25', 91),
('The Hills', 'The Weeknd', 'R&B', 'UK', 'London', '26-40', 92),
('Earned It', 'The Weeknd', 'R&B', 'UK', 'London', '26-40', 89),
('Often', 'The Weeknd', 'R&B', 'UK', 'London', '26-40', 88),
('Don''t Start Now', 'Dua Lipa', 'Pop', 'UK', 'Manchester', '19-25', 94),
('Physical', 'Dua Lipa', 'Pop', 'UK', 'Manchester', '19-25', 91),
('New Rules', 'Dua Lipa', 'Pop', 'UK', 'Manchester', '13-18', 93),
('IDGAF', 'Dua Lipa', 'Pop', 'UK', 'Manchester', '19-25', 90),
('Be the One', 'Dua Lipa', 'Pop', 'UK', 'Manchester', '19-25', 88),
('Hotter Than Hell', 'Dua Lipa', 'Pop', 'UK', 'Birmingham', '19-25', 87),
('One Kiss', 'Dua Lipa', 'Electronic', 'UK', 'Birmingham', '19-25', 92),
('Electricity', 'Dua Lipa', 'Electronic', 'UK', 'Birmingham', '19-25', 89),
('Break My Heart', 'Dua Lipa', 'Pop', 'UK', 'Birmingham', '13-18', 90),
('Hallucinate', 'Dua Lipa', 'Pop', 'UK', 'Birmingham', '13-18', 88),

-- More India entries
('Tere Vaaste', 'Varun Jain', 'Bollywood', 'India', 'Delhi', '13-18', 91),
('O Maahi', 'Arijit Singh', 'Bollywood', 'India', 'Delhi', '19-25', 90),
('Aaj Ki Raat', 'Madhubanti Bagchi', 'Bollywood', 'India', 'Delhi', '19-25', 89),
('Tauba Tauba', 'Karan Aujla', 'Punjabi', 'India', 'Delhi', '13-18', 92),
('Satranga', 'Arijit Singh', 'Bollywood', 'India', 'Mumbai', '19-25', 93),
('Pehle Bhi Main', 'Vishal Mishra', 'Bollywood', 'India', 'Mumbai', '19-25', 91),
('Maan Meri Jaan', 'King', 'Hip-Hop', 'India', 'Mumbai', '19-25', 90),
('Tu Hai Kahan', 'AUR', 'Indie', 'India', 'Mumbai', '19-25', 88),
('Kesariya', 'Pritam', 'Bollywood', 'India', 'Bengaluru', '19-25', 94),
('What Jhumka?', 'Arijit Singh', 'Bollywood', 'India', 'Bengaluru', '13-18', 91),
('Heeriye', 'Arijit Singh', 'Punjabi', 'India', 'Chennai', '19-25', 90),
('Arjan Vailly', 'Bhupinder Babbal', 'Punjabi', 'India', 'Hyderabad', '19-25', 92),
('Agar Ho Tum', 'Mr. & Mrs. Mahi', 'Bollywood', 'India', 'Pune', '19-25', 88),
('Kahani Suno', 'Kaifi Khalil', 'Pop', 'India', 'Calicut', '19-25', 87),

-- More Japan entries
('KICK BACK', 'Kenshi Yonezu', 'J-Pop', 'Japan', 'Tokyo', '13-18', 96),
('Suzume', 'RADWIMPS', 'J-Pop', 'Japan', 'Tokyo', '13-18', 94),
('LADY', 'Kenshi Yonezu', 'J-Pop', 'Japan', 'Tokyo', '19-25', 92),
('Shinunoga E-Wa', 'Fujii Kaze', 'J-Pop', 'Japan', 'Tokyo', '19-25', 93),
('Matsuri', 'Fujii Kaze', 'J-Pop', 'Japan', 'Osaka', '19-25', 90),
('Kirari', 'Fujii Kaze', 'J-Pop', 'Japan', 'Osaka', '26-40', 89),
('Grace', 'Fujii Kaze', 'J-Pop', 'Japan', 'Kyoto', '26-40', 88),
('Damn', 'Fujii Kaze', 'J-Pop', 'Japan', 'Kyoto', '19-25', 87),

-- More South Korea entries
('Magnetic', 'ILLIT', 'K-Pop', 'South Korea', 'Seoul', '13-18', 93),
('Supernova', 'aespa', 'K-Pop', 'South Korea', 'Seoul', '13-18', 94),
('Armageddon', 'aespa', 'K-Pop', 'South Korea', 'Busan', '13-18', 92),
('Drama', 'aespa', 'K-Pop', 'South Korea', 'Busan', '13-18', 91),
('Spicy', 'aespa', 'K-Pop', 'South Korea', 'Incheon', '13-18', 90),
('Next Level', 'aespa', 'K-Pop', 'South Korea', 'Incheon', '13-18', 95),
('Savage', 'aespa', 'K-Pop', 'South Korea', 'Seoul', '13-18', 93),
('Black Mamba', 'aespa', 'K-Pop', 'South Korea', 'Seoul', '13-18', 91),

-- More France entries
('Mon Amour', 'Stromae', 'Pop', 'France', 'Paris', '19-25', 90),
('La Solassitude', 'Stromae', 'Pop', 'France', 'Paris', '26-40', 88),
('L''amour Toujours', 'Gigi D''Agostino', 'Electronic', 'France', 'Lyon', '26-40', 91),
('Voyage Voyage', 'Desireless', 'Pop', 'France', 'Lyon', '40+', 89),
('Pour Que Tu M''Aimes Encore', 'Celine Dion', 'Pop', 'France', 'Marseille', '40+', 94),
('S''il Suffisait D''Aimer', 'Celine Dion', 'Pop', 'France', 'Marseille', '40+', 92),

-- Additional cross-regional popular songs
('Electric Feel', 'MGMT', 'Indie', 'USA', 'Houston', '19-25', 89),
('Time to Pretend', 'MGMT', 'Indie', 'USA', 'New York', '19-25', 87),
('Kids', 'MGMT', 'Indie', 'USA', 'Los Angeles', '19-25', 88),
('Riptide', 'Vance Joy', 'Indie', 'USA', 'Chicago', '19-25', 90),
('Budapest', 'George Ezra', 'Pop', 'UK', 'London', '19-25', 89),
('Shotgun', 'George Ezra', 'Pop', 'UK', 'Manchester', '19-25', 88),
('Paradise', 'George Ezra', 'Pop', 'UK', 'Birmingham', '13-18', 86);